Week14/AppDersAtama/AppDersAtama/Models/Entity/Ogrenci.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppDersAtama.Models.Entity
{
    public class Ogrenci
    {
        public int OgrenciId { get; set; }
        public int OgrenciNo { get; set; }
        public string OgrenciAd { get; set; }
        public string OgrenciSoyad { get; set; }
        public DateTime OgrenciDogumTarihi { get; set; }
        public DateTime OgrenciKayitTarihi { get; set; }
        public sbyte Donem { get; set; }
        public Bolum Bolum { get; set; }
        public int BolumId { get; set; }
        public List<OgrenciDers> OgrenciDersler { get; set; }
    }
}

Week14/AppDersAtama/AppDersAtama/Controllers/OgrenciController.cs
using AppDersAtama.Models;
using AppDersAtama.Models.EF;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppDersAtama.Controllers
{
    public class OgrenciController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AssignLesson()
        {
            var model = new EFOgrenciDal();
            return View(model.GetAll());
        }

        public IActionResult Assign(int id)
        {
            var model2 = new EFDersDal();
            var context = new EFOgrenciDal();
            var entity = context.GetByIdWithDersler(id);
            var model = new OgrenciModel()
            {
                OgrenciId = entity.OgrenciId,
                OgrenciNo = entity.OgrenciNo,
                OgrenciAd = entity.OgrenciAd,
                OgrenciSoyad = entity.OgrenciSoyad,
                OgrenciDogumTarihi = entity.OgrenciDogumTarihi,
                OgrenciKayitTarihi = entity.OgrenciKayitTarihi,
                Donem = entity.Donem,
                BolumId = entity.BolumId,
                SecilenDersler = entity.OgrenciDersler.Select(x => x.Ders).ToList()
            };
            ViewBag.Dersler = model2.GetAll();
            return View(model);
        }
    }
}

Week14/AppDersAtama/AppDersAtama/Views/Ogrenci/Assign.cshtml
@model AppDersAtama.Models.OgrenciModel


    <h5 class="display-4">Assign Lesson</h5>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label class="col-form-label text-danger">Öğrenci Ad: </label>
                <label class="col-form-label">@Model.OgrenciAd</label>
            </div>
            <div class="form-group">
                <label class="col-form-label text-danger">Öğrenci Soyad: </label>
                <label class="col-form-label">@Model.OgrenciSoyad</label>
            </div>
        </div>
        <div class="col-md-8">
            @for (int i = 0; i < Model.SecilenDersler.Count; i++)
            {
                <input type="hidden" name="SecilenDersler[@i].DersId" value="@Model.SecilenDersler[i].DersId" />
                <input type="hidden" name="SecilenDersler[@i].DersAd" value="@Model.SecilenDersler[i].DersAd" />
            }
            @foreach (var item in (List<AppDersAtama.Models.Entity.Ders>)ViewBag.Dersler)
            {
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="@item.DersId" name="DersId" id="ders_@item.DersId" @(Model.SecilenDersler.Any(x => x.DersId == item.DersId) ? "checked" : "") />
                    <label class="form-check-label" for="ders_@item.DersId">@item.DersAd</label>
                </div>
            }
        </div>
    </div>

Week14/AppDersAtama/AppDersAtama/Views/Ogrenci/AssignLesson.cshtml
@model List<AppDersAtama.Models.Entity.Ogrenci>

<h5 class="display-4">Assign Lesson</h5>
<hr />
<div class="row">
    <div class="col-md-12">
        <table class="table table-sm table-bordered">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>No</td>
                    <td>Öğrenci Ad</td>
                    <td>Öğrenci Soyad</td>
                    <td>Dönem</td>
                    <td>Bölüm</td>
                    <td>Alınan Dersler</td>
                    <td>Aldığı Dersler</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
    <tr>
        <td>@item.OgrenciId</td>
        <td>@item.OgrenciNo</td>
        <td>@item.OgrenciAd</td>
        <td>@item.OgrenciSoyad</td>
        <td>@item.Donem</td>
        <td>@item.Bolum</td>
        <td></td>
        <td>
            <a asp-controller="Ogrenci" asp-action="Assign" asp-route-id="@item.OgrenciId" class="btn btn-sm btn-primary">Assign Lesson</a>
        </td>
    </tr>}
            </tbody>
        </table>
    </div>

</div>

Week14/AppDersAtama/AppDersAtama/Views/Ogrenci/Index.cshtml
@model List<AppDersAtama.Models.Entity.Ogrenci>

@{
    ViewData["Title"] = "Index";
}

<h1 class="bg-dark text-light">Öğrenciler</h1>

<a asp-action="Create">Öğrenci Kaydet</a>

<table class="table table-dark text-white">
    <thead>
        <tr>
            <th>Öğrenci Id</th>
            <th>Öğrenci No</th>
            <th>Öğrenci Ad</th>
            <th>Öğrenci Soyad</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ogrenci in Model)
        {
            <tr>
                <td>@ogrenci.OgrenciId</td>
                <td>@ogrenci.OgrenciNo</td>
                <td>@ogrenci.OgrenciAd</td>
                <td>@ogrenci.OgrenciSoyad</td>
                <td class="d-flex">
                    <a class="btn mx-1 btn-sm btn-success" asp-action="Details" asp-route-id="@ogrenci.OgrenciId">Detaylar</a>
                    <a class="btn mx-1 btn-sm btn-warning" asp-action="Edit" asp-route-id="@ogrenci.OgrenciId">Düzenle</a>
                    <a class="btn mx-1 btn-sm btn-danger" asp-action="Delete" asp-route-id="@ogrenci.OgrenciId">Sil</a>
                    <a asp-controller="Ogrenci" asp-action="Assign" asp-route-id="@ogrenci.OgrenciId" class="btn btn-sm btn-primary">Assign Lesson</a>
                </td>
            </tr>
        }
    </tbody>
</table>