Week14/YemekTarifleriApp/YemekTarifleriApp.WebUI/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YemekTarifleriApp.Bussiness.Abstract;
using YemekTarifleriApp.Entity;
using YemekTarifleriApp.WebUI.Models;

namespace YemekTarifleriApp.WebUI.Controllers
{
    public class RecipeController : Controller
    {
        private IRecipeService _recipeService;
        public RecipeController(IRecipeService recipeService)
        {
            _recipeService = recipeService;
        }
        public IActionResult Index()
        {
            return View(_recipeService.GetAll());
        }
        public IActionResult Details(string url)
        {
            if (url == null)
            {
                return NotFound();
            }
            Recipe recipe = _recipeService.GetRecipeDetails(url);
            if (recipe == null)
            {
                return NotFound();
            }
            RecipeDetailModel recipeDetail = new RecipeDetailModel()
            {
                Recipe = recipe,
                Categories = recipe.RecipeCategories.Select(i => i.Category).ToList()
            };
            return View(recipeDetail);
        }
        public IActionResult List(string category, int page = 1)
        {
            ViewBag.Message = "Ürün bulunamadı";
            ViewBag.AlertType = "warning";


            const int pageSize = 5;
            int totalItems = _recipeService.GetCountByCategory(category);
            var productListViewModel = new RecipeListViewModel()
            {
                PageInfo = new PageInfo
                {
                    TotalItems = totalItems,
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category
                },
                Recipes = _recipeService.GetRecipesByCategory(category, page, pageSize)
            };
          
            return View(productListViewModel);
        }
    }
}

Week14/YemekTarifleriApp/YemekTarifleriApp.WebUI/ViewComponents/CategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YemekTarifleriApp.Bussiness.Abstract;

namespace YemekTarifleriApp.WebUI.ViewComponents
{
    public class CategoriesViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoriesViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["category"] != null)
            {
                ViewBag.SelectedCategory = RouteData.Values["category"];
            }
            return View(_categoryService.GetAll());
        }
    }
}

Week14/YemekTarifleriApp/YemekTarifleriApp.WebUI/Views/Recipe/Details.cshtml
@model YemekTarifleriApp.WebUI.Models.RecipeDetailModel

<div class="row" style="height:480px;">
    <div class="col-md-2">
        <img src="~/img/@Model.Recipe.ImageUrl" class="img-fluid" alt="Alternate Text" />
    </div>
    <div class="col-md-10">
        <h1 class="mb-3 text-white">@Model.Recipe.RecipeName</h1>
        <hr />
        @foreach (var recipe in Model.Categories)
        {
            <a asp-controller="Recipe"
               asp-action="Details"
               asp-route-category="@recipe.Url"
               class="btn btn-link p-0 mb-3">@recipe.CategoryName </a>}
        <div class="mb-3">
            <div class="mb-3">
                <p>@Model.Recipe.RecipeMaterial</p>
                <p>@Model.Recipe.RecipeDescription</p>
                <p class="card-text">@Model.Recipe.RecipeReleaseDate</p>
            </div>
        </div>
    </div>
</div>

Week14/YemekTarifleriApp/YemekTarifleriApp.WebUI/Views/Recipe/List.cshtml
@model YemekTarifleriApp.WebUI.Models.RecipeListViewModel

<div class="row">
    <div class="col-md-9">
        <div class="row">

            @foreach (var recipeList in Model.Recipes)
            {
                <div class="col-md-4">
                    @await Html.PartialAsync("_RecipeList", recipeList)
                </div>
            }
        </div>
        <div class="row">
            <div class="col">
                <nav>
                    <ul class="pagination">
                        @for (int i = 0; i < Model.PageInfo.TotalPages(); i++)
                        {
                            @if (string.IsNullOrEmpty(Model.PageInfo.CurrentCategory))
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage==i+1 ? "active" : "")">
                                    <a href="/foods?page=@(i+1)" class="page-link">@(i+1)</a>
                                </li>
                            }
                            else
                            {
                                <li class="page-item @(Model.PageInfo.CurrentPage==i+1 ? "active" : "")">
                                    <a href="/foods/@Model.PageInfo.CurrentCategory?page=@(i+1)" class="page-link">@(i+1)</a>
                                </li>
                            }
                        }
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="row">
            @await Component.InvokeAsync("Categories")

        </div>
    </div>
</div>