Week15/MiniShopApp-eski/MiniShopApp.WebUI/Controllers/CardController.cs
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MiniShopApp.Business.Abstract;
using MiniShopApp.Core;
using MiniShopApp.Entity;
using MiniShopApp.WebUI.Identity;
using MiniShopApp.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OrderItem = MiniShopApp.Entity.OrderItem;

namespace MiniShopApp.WebUI.Controllers
{
    [Authorize]
    public class CardController : Controller
    {
        private ICardService _cardService;
        private UserManager<User> _userManager;
        private IOrderService _orderService;

        public CardController(ICardService cardService, UserManager<User> userManager, IOrderService orderService)
        {
            _cardService = cardService;
            _userManager = userManager;
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            var card = _cardService.GetCardByUserId(_userManager.GetUserId(User));
            var model = new CardModel()
            {
                CardId = card.Id,
                CardItems = card.CardItems.Select(i => new CardItemModel()
                {
                    CardItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            };
            return View(model);
        }

        public IActionResult GetOrders()
        {
            var userId = _userManager.GetUserId(User);
            var orders = _orderService.GetOrders(userId);
            var orderListModel = new List<OrderListModel>();
            OrderListModel orderModel;
            foreach (var order in orders)
            {
                orderModel = new OrderListModel();
                orderModel.OrderId = order.Id;
                orderModel.OrderNumber = order.OrderNumber;
                orderModel.Address = order.Address;
                orderModel.OrderDate = order.OrderDate;
                orderModel.City = order.City;
                orderModel.FirstName = order.FirstName;
                orderModel.LastName = order.LastName;
                orderModel.Note = order.Note;
                orderModel.Phone = order.Phone;
                orderModel.Email = order.Email;
                orderModel.OrderState = order.OrderState;
                orderModel.PaymentType = order.PaymentType;
                orderModel.OrderItems = order.OrderItems.Select(i => new OrderItemModel()
                {
                    OrderItemId=i.Id,
                    Name=i.Product.Name,
                    Price=(double)i.Price,
                    Quantity=i.Quantity,
                    ImageUrl=i.Product.ImageUrl
                }).ToList();

                orderListModel.Add(orderModel);
            }
            return View("Orders",orderListModel);
        }

        [HttpPost]
        public IActionResult AddToCard(int productId, int quantity)
        {
            var userId = _userManager.GetUserId(User);
            _cardService.AddToCard(userId, productId, quantity);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteFromCard(int productId)
        {
            var userId = _userManager.GetUserId(User);
            _cardService.DeleteFromCard(userId, productId);
            return RedirectToAction("Index");
        }
        public IActionResult CheckOut()
        {
            var userId = _userManager.GetUserId(User);
            var card = _cardService.GetCardByUserId(userId);
            var orderModel = new OrderModel();
            orderModel.CardModel = new CardModel()
            {
                CardId = card.Id,
                CardItems = card.CardItems.Select(i => new CardItemModel()
                {
                    CardItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            };

            return View(orderModel);
        }

        [HttpPost]
        public IActionResult CheckOut(OrderModel orderModel)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var card = _cardService.GetCardByUserId(userId);
                orderModel.CardModel = new CardModel()
                {
                    CardId = card.Id,
                    CardItems = card.CardItems.Select(i => new CardItemModel()
                    {
                        CardItemId = i.Id,
                        ProductId = i.ProductId,
                        Name = i.Product.Name,
                        Price = (double)i.Product.Price,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity
                    }).ToList()
                };
                //Ödeme işlemine başla
                if (!CardNumberControl(orderModel.CardNumber))
                {
                    TempData["Message"] = JobManager.CreateMessage("HATA", "Kart numarasını kontrol ediniz!", "danger");
                    return View(orderModel);
                }
                var payment = PaymentProcess(orderModel);
                if (payment.Status=="success")
                {
                    SaveOrder(orderModel, payment, userId);
                    _cardService.ClearCard(card.Id);
                    TempData["Message"] = JobManager.CreateMessage("BİLGİ", "Ödemeniz başarıyla gerçekleştirilmiştir!", "success");
                    return Redirect("~/");
                }
                else
                {
                    TempData["Message"] = JobManager.CreateMessage("DİKKAT!", payment.ErrorMessage , "danger");
                   
                }
            }
            return View(orderModel);
        }

        private void SaveOrder(OrderModel orderModel, Payment payment, string userId)
        {
            var order = new Order();
            order.OrderNumber = new Random().Next(111111111, 999999999).ToString();
            order.OrderState = EnumOrderState.Completed;
            order.PaymentType = EnumPaymentType.CreditCard;
            order.PaymentId = payment.PaymentId;
            order.ConversationId = payment.ConversationId;
            order.OrderDate = DateTime.Now;
            order.FirstName = orderModel.FirstName;
            order.LastName = orderModel.LastName;
            order.UserId = userId;
            order.Address = orderModel.Address;
            order.City = orderModel.City;
            order.Phone = orderModel.Phone;
            order.Email = orderModel.Email;
            order.Note = orderModel.Note;

            order.OrderItems = new List<OrderItem>();
            foreach (var item in orderModel.CardModel.CardItems)
            {
                var orderItem = new OrderItem()
                {
                    Price=item.Price,
                    Quantity=item.Quantity,
                    ProductId=item.ProductId
                };
                order.OrderItems.Add(orderItem);
            }
            _orderService.Create(order);

        }

        private Payment PaymentProcess(OrderModel orderModel)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-2cOZxeLZDfeUJEwwf7pn6rxDfLHm5Qyv";
            options.SecretKey = "sandbox-LeC9S7gFn8WZWxaomdxOggXfkBrlsYBb";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";

            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = new Random().Next(111111111, 999999999).ToString();
            request.Price = orderModel.CardModel.TotalPrice().ToString();
            request.PaidPrice = orderModel.CardModel.TotalPrice().ToString();
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = "B67832";
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = orderModel.CardName;
            //Card Number Luhn Algoritması ile kontrol edilmeli ve doğru ise buraya atanmalıdır.
            paymentCard.CardNumber = orderModel.CardNumber;
            paymentCard.ExpireMonth = orderModel.ExpirationMonth;
            paymentCard.ExpireYear = orderModel.ExpirationYear;
            paymentCard.Cvc = orderModel.Cvc;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;

            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = orderModel.FirstName;
            buyer.Surname = orderModel.LastName;
            buyer.GsmNumber = orderModel.Phone;
            buyer.Email = orderModel.Email;
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = orderModel.Address;
            buyer.Ip = "85.34.78.112";
            buyer.City = orderModel.City;
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;


Week15/MiniShopApp-eski/MiniShopApp.WebUI/Controllers/MiniShopController.cs
using Microsoft.AspNetCore.Mvc;
using MiniShopApp.Business.Abstract;
using MiniShopApp.Entity;
using MiniShopApp.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MiniShopApp.WebUI.Controllers
{
    public class MiniShopController : Controller
    {
        private IProductService _productService;
        public MiniShopController(IProductService productService)
        {
            _productService=productService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult List(string category, int page=1)
        {
            ViewBag.Message = "Ürün bulunamadı";
            ViewBag.AlertType = "warning";
            //ÖDEV:
            //Bu işi ister model kullanarak şu an olduğu gibi partial yapıyla
            //İsterseniz ise daha farklı bir yol olarak ViewComponent mantığıyla
            //Çözün.

            //***********************************

            const int pageSize = 5;//bu değişken her sayfada kaç item görüneceğini tutacak
            int totalItems = _productService.GetCountByCategory(category);
            var productListViewModel = new ProductListViewModel()
            {
                PageInfo = new PageInfo
                {
                    TotalItems= totalItems,
                    CurrentPage= page,
                    ItemsPerPage= pageSize,
                    CurrentCategory = category
                },
                Products= _productService.GetProductsByCategory(category, page, pageSize)
            };
            return View(productListViewModel); 
        }

        public IActionResult Details(string url)
        {
            if (url==null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails(url);
            if (product==null)
            {
                return NotFound();
            }
            ProductDetailModel productDetail = new ProductDetailModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(i => i.Category).ToList() 
            };
            return View(productDetail);  
        }

        public IActionResult Search(string q)
        {
            //Bize arama kriterinin (q) uygun olduğu, eşleştiği TÜM ÜRÜNLERİ
            //döndürecek bir METOT lazım.
            return View(_productService.GetSearchResult(q)); 
        }
    }
}

Week15/MiniShopApp-eski/MiniShopApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiniShopApp.WebUI</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    @RenderSection("Css", false)
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <partial name="_NavBar" />
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["Message"] != null)
            {
                var message = JsonConvert.DeserializeObject<AlertMessage>(TempData["Message"] as String);
                <div class="row">
                    <div class="col-md-12 alert">
                        <div class="alert alert-@message.AlertType alert-dismissible fade show" role="alert">
                            <div>@message.Title</div>
                            <div>@message.Message</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MiniShopApp.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js" integrity="sha512-6PM0qYu5KExuNcKt5bURAoT6KCThUmHRewN3zUFNaoI6Di7XJPTMoT6K0nsagZKk2OB4L7E3q1uQKHNHd4stIQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", false)
</body>
</html>

Week15/MiniShopApp-eski/MiniShopApp.WebUI/Views/Shared/_NavBar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MiniShopApp.WebUI</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <div>
                    <ul class="navbar-nav flex-grow-1">


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MiniShop" asp-action="List" asp-route-category="">Products</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a href="card" class="nav-link text-dark">Card</a>
                            </li>
                           
                            <li class="nav-item">
                                <a href="orders" class="nav-link text-dark">Orders</a>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a href="/admin/products" class="nav-link text-dark">Admin Products</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/admin/role/list" class="nav-link text-dark">Roles</a>
                                </li>
                                <li class="nav-item">
                                    <a href="/admin/user/list" class="nav-link text-dark">Users</a>
                                </li>
                            }

                        }

                    </ul>
                </div>
                <div>

                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a href="/account/login" class="nav-link text-dark">Login</a>
                            </li>
                            <li class="nav-item">
                                <a href="/account/register" class="nav-link text-dark">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a href="/account/manage" class="nav-link text-dark">@User.Identity.Name </a>
                            </li>
                            <li class="nav-item">
                                <a href="/account/logout" class="nav-link text-dark">Logout</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>

Week15/MiniShopApp-eski/MiniShopApp.WebUI/Views/Shared/_NoProduct.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-@ViewBag.AlertType">
             @ViewBag.Message
        </div>
    </div>
</div>

Week15/MiniShopApp-eski/MiniShopApp.WebUI/Views/Shared/_Product.cshtml
@model Product
<div class="card mb-2">
    <div class="card-img p-2 text-md-center">
        <img src="~/img/@Model.ImageUrl" class="img-fluid" />
    </div>

    <div class="card-body">
        <h5 class="card-title text-center">@Model.Name</h5>
        <small class="text-muted">
            <i class="fa-solid fa-turkish-lira-sign"></i>@Model.Price
        </small>
        <div class="card-footer bg-white text-center d-flex justify-content-around p-1">
            <a asp-controller="MiniShop"
               asp-action="Details"
               asp-route-url=@Model.Url
               class="btn btn-sm btn-primary">Detail</a>
            @if (User.Identity.IsAuthenticated)
            {
                <form asp-controller="Card" asp-action="AddToCard" method="post">
                    <input type="hidden" name="productId" value="@Model.ProductId" />
                    <input type="hidden" name="quantity" value="1" />
                    <button type="submit" class="btn btn-sm btn-primary">Add To Card</button>
                </form>
            }
        </div>
    </div>
</div>